import Head from 'next/head'
import styles from '@/styles/Home.module.css'
import { useState } from 'react'
import { useRouter } from 'next/router'

export default function Home() {
  const router = useRouter()
  const [name, setName] = useState();
  const [age, setAge] = useState();
  async function submitData(e) {
    e.preventDefault()
    await fetch('/api/setData', {
      method: 'POST',
      headers: {
        'Accept': 'application/json',
        'Content-Type': 'application/json'
      },
      body: JSON.stringify({ fullName: name, age: age })
    });
    router.push({ pathname: '/show' })
  }
  return (
    <>
      <Head>
        <title>Next JS App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <form onSubmit={submitData}>
          <label>Enter Full Name:</label>
          <input type="text" onChange={(e) => setName(e.target.value)} /><br /><br />
          <label>Enter Age:</label>
          <input type="number" onChange={(e) => setAge(e.target.value)} /><br />
          <input type="submit" />
        </form>
      </main>
    </>
  )
}
